---
-- #%L
-- JSQLParser library
-- %%
-- Copyright (C) 2004 - 2026 JSQLParser
-- %%
-- Dual licensed under GNU LGPL 2.1 or Apache License 2.0
-- #L%
---
CREATE ROLE replicator WITH REPLICATION LOGIN PASSWORD 'example-only'
CREATE ROLE app
CREATE ROLE login
CREATE ROLE admin WITH SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN BYPASSRLS
CREATE ROLE guest NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN NOREPLICATION NOBYPASSRLS
CREATE ROLE reader WITH CONNECTION LIMIT -1 PASSWORD NULL
CREATE ROLE analyst ENCRYPTED PASSWORD 'example-only' VALID UNTIL '2030-01-01'
CREATE ROLE member IN ROLE reader, writer
CREATE ROLE staff IN GROUP reader ROLE app, analyst ADMIN owner USER member
CREATE ROLE legacy SYSID 100
CREATE ROLE "Mixed Role" LOGIN
CREATE USER app_user WITH LOGIN PASSWORD 'example-only'
CREATE USER app_user NOLOGIN
CREATE GROUP app_group
CREATE GROUP staff WITH USER app, analyst
ALTER ROLE replicator CONNECTION LIMIT 10
ALTER ROLE app WITH LOGIN NOSUPERUSER PASSWORD NULL
ALTER ROLE app ENCRYPTED PASSWORD 'example-only' VALID UNTIL 'infinity'
ALTER ROLE app RENAME TO new_app
ALTER ROLE CURRENT_USER SET search_path TO app, public
ALTER ROLE CURRENT_ROLE IN DATABASE appdb SET statement_timeout = '5s'
ALTER ROLE ALL SET work_mem TO DEFAULT
ALTER ROLE app SET work_mem FROM CURRENT
ALTER ROLE app RESET work_mem
ALTER ROLE ALL IN DATABASE appdb RESET ALL
ALTER USER app_user WITH NOLOGIN
ALTER USER SESSION_USER SET enable_seqscan TO on
ALTER GROUP staff ADD USER app, analyst
ALTER GROUP staff DROP USER analyst
ALTER GROUP staff RENAME TO team
GRANT SELECT ON app.users TO reader
GRANT SELECT ON type TO app
GRANT SELECT ON tables TO app
GRANT SELECT ON function TO granted
GRANT SELECT ON tables, types TO app
GRANT SELECT ON type.items TO app
GRANT SELECT, INSERT, UPDATE ON TABLE app.users, app.orders TO reader, writer
GRANT SELECT (id, name), UPDATE (name) ON app.users TO app
GRANT ALL PRIVILEGES ON TABLE app.users TO PUBLIC WITH GRANT OPTION
GRANT REFERENCES (id) ON app.users TO GROUP app
GRANT TRUNCATE, TRIGGER, MAINTAIN ON app.users TO owner
GRANT USAGE, SELECT, UPDATE ON SEQUENCE app.user_id_seq TO app
GRANT ALL ON ALL SEQUENCES IN SCHEMA app, public TO app
GRANT SELECT ON ALL TABLES IN SCHEMA app TO reader
GRANT CREATE, CONNECT, TEMPORARY ON DATABASE appdb TO app
GRANT TEMP ON DATABASE appdb TO app
GRANT USAGE ON DOMAIN app.positive_int TO app
GRANT USAGE ON FOREIGN DATA WRAPPER postgres_fdw TO app
GRANT USAGE ON FOREIGN SERVER foreign_server TO app
GRANT EXECUTE ON FUNCTION add(integer, integer) TO app
GRANT EXECUTE ON FUNCTION app.f(IN value integer, VARIADIC args text[]) TO app
GRANT EXECUTE ON FUNCTION app.no_args(), app.unspecified TO app
GRANT EXECUTE ON PROCEDURE app.process(integer) TO app
GRANT EXECUTE ON ROUTINE app.process(integer) TO CURRENT_USER
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA app TO PUBLIC
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA app TO app
GRANT EXECUTE ON ALL ROUTINES IN SCHEMA app TO app
GRANT USAGE ON LANGUAGE plpgsql TO app
GRANT SELECT, UPDATE ON LARGE OBJECT 123, 456 TO app
GRANT SET, ALTER SYSTEM ON PARAMETER work_mem, maintenance_work_mem TO app
GRANT USAGE, CREATE ON SCHEMA public TO app GRANTED BY CURRENT_ROLE
GRANT CREATE ON TABLESPACE appspace TO app
GRANT USAGE ON TYPE app.status TO app
GRANT reader, writer TO app WITH ADMIN OPTION
GRANT reader TO app WITH INHERIT FALSE
GRANT reader TO app WITH SET TRUE GRANTED BY owner
REVOKE EXECUTE ON FUNCTION add(integer, integer) FROM app
REVOKE GRANT OPTION FOR SELECT ON TABLE app.users FROM app CASCADE
REVOKE SELECT (id) ON app.users FROM app RESTRICT
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA app FROM PUBLIC
REVOKE USAGE ON SCHEMA public FROM app GRANTED BY CURRENT_USER CASCADE
REVOKE reader, writer FROM app
REVOKE ADMIN OPTION FOR reader FROM app CASCADE
REVOKE INHERIT OPTION FOR reader FROM app RESTRICT
REVOKE SET OPTION FOR reader FROM app GRANTED BY owner
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO app
ALTER DEFAULT PRIVILEGES FOR ROLE owner, admin IN SCHEMA app, public GRANT USAGE ON SEQUENCES TO app WITH GRANT OPTION
ALTER DEFAULT PRIVILEGES FOR USER owner REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC
ALTER DEFAULT PRIVILEGES GRANT EXECUTE ON ROUTINES TO app
ALTER DEFAULT PRIVILEGES GRANT USAGE ON TYPES TO app
ALTER DEFAULT PRIVILEGES GRANT CREATE ON SCHEMAS TO app
ALTER DEFAULT PRIVILEGES GRANT SELECT ON LARGE OBJECTS TO app
ALTER DEFAULT PRIVILEGES REVOKE GRANT OPTION FOR SELECT ON TABLES FROM app CASCADE
CREATE TRIGGER audit_trigger AFTER INSERT OR UPDATE ON users FOR EACH ROW EXECUTE FUNCTION audit_row()
CREATE CONSTRAINT TRIGGER fk_trigger AFTER INSERT ON child DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_parent()
CREATE CONSTRAINT TRIGGER fk_trigger AFTER UPDATE ON child FROM parent NOT DEFERRABLE FOR EACH ROW EXECUTE FUNCTION check_parent()
CREATE CONSTRAINT TRIGGER fk_trigger AFTER INSERT ON child INITIALLY IMMEDIATE FOR EACH ROW EXECUTE PROCEDURE check_parent()
CREATE OR REPLACE TRIGGER audit_trigger BEFORE UPDATE OF balance, owner ON accounts FOR EACH ROW WHEN (OLD.balance IS DISTINCT FROM NEW.balance) EXECUTE FUNCTION audit_row('balance', 1, flag)
CREATE TRIGGER insert_view INSTEAD OF INSERT ON app.users_view FOR EACH ROW EXECUTE FUNCTION app.insert_row()
CREATE TRIGGER truncate_audit AFTER TRUNCATE ON users EXECUTE FUNCTION audit_all()
CREATE TRIGGER statement_audit AFTER DELETE ON users FOR STATEMENT EXECUTE FUNCTION audit_all()
CREATE TRIGGER update_audit AFTER UPDATE ON users REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION audit_all()
CREATE TRIGGER insert_audit AFTER INSERT ON users REFERENCING NEW TABLE inserted FOR EACH STATEMENT EXECUTE PROCEDURE audit_all()
CREATE TRIGGER row_audit AFTER UPDATE ON users FOR ROW WHEN (OLD.id <> NEW.id) EXECUTE FUNCTION audit_row()
CREATE TRIGGER "Mixed Trigger" BEFORE DELETE ON "App"."Users" FOR EACH ROW EXECUTE FUNCTION "App"."audit_row"('it''s an example')
